learning_log/urls.py
from django.contrib import admin
from django.urls import path,include


app_name='learning_logs'

urlpatterns = [

    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('', include('learning_logs.urls')),
   
]

learning_logs/urls.py
"""Define url patterns"""

from django.urls import path
from . import views

app_name='learning_logs'


urlpatterns=[
    
    #Home page
    path('', views.index, name='index'),

    #all topics
    path('topics/', views.topics, name='topics'),
    path('topic/<topic_id>/',views.topic,name='topic'),
    path('new_topic',views.new_topic,name='new_topic')
    ]

tutorial/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views
app_name="users"
urlpatterns=[
    path('login/',LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/',LogoutView.as_view(),name="logout"),
    path('register', views.register, name='register'),

]

learning_logs/models.py
from django.db import models


# Create your models here.

class Topic(models.Model):
    text=models.CharField(max_length=200)
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.text

class Entry(models.Model):
    """something specific about a topic"""
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural ='entries'
    def __str__(self):
        if len(self.text) > 50:
            return self.text[:50] + "...."
        else:
            return self.text

models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic
class PersonForm(forms.ModelForm):
    class Meta:
        model=Topic
        fields=['text']
        labels={"text":''}

learning_logs/views.py
from django.shortcuts import render
from .models import Topic
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import PersonForm
from django.contrib.auth.views import LogoutView,LoginView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate


# Create your views here.

def index(request):

    return render(request, 'learning_logs/index.html')

def topics(request):
    topics=Topic.objects.order_by('date_added')
    context={'topics':topics}
    return render(request, 'learning_logs/topics.html', context)


def topic(request,topic_id):
    topic=Topic.objects.get(id=topic_id)
    entries=topic.entry_set.all()
    context={'topic':topic,'entries':entries}
    return render(request,'learning_logs/topic.html',context)

def new_topic(request):


    if request == 'POST':
        form = PersonForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    else:
        form =PersonForm()
    context={'form':form}
    return render(request, 'learning_logs/new_topic.html',context)

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm


# Create your views here.

def register(request):
    if request.method =='POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user=form.save()
            authenticated_user=authenticate(username=new_user.username)
            LoginView(request, authenticated_user)
            return HttpResposeredirect(reverse, "learning_logs:index")
    else:
        form=UserCreationForm()    
    context={'form':form}        
    return render(request,'users/register.html',context)

views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from rest_framework import permissions
from tutorial.quickstart.serializers import UserSerializer, GroupSerializer


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = [permissions.IsAuthenticated]

learning_logs/templates/learning_logs/base.html
<p>
    <a href="{%url 'learning_logs:index'%}">Learning Log</a> -
    <a href="{%url 'learning_logs:topics'%}">Topics</a> -
   {% if user.is_authenticated %}
     Hello , {{user.username}}
   {%else%}
     <a href="{% url 'users:login'%}">login</a>
    {%endif%}
</p>

{%block content %}{% endblock content%}

learning_logs/templates/learning_logs/index.html
{%extends "learning_logs/base.html"%}

{% block content %}


<p>Learning log helps keep track of all the topics you have learned about</p>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{%block content%}

<p> Add a new topic</p>
<form method="post">
    {%csrf_token%}
{{form.as_p}}
<button name="submit">Add topic</button>
</form>



{%endblock content%}

learning_logs/templates/learning_logs/topic.html
{%block content%}


<p>{{topic}}</p>
{%for entry  in entries%}
<li>{{entry.text}}</li>
{%empty%}
<p>No entry added</p>
{%endfor%}

{%endblock content%}

learning_logs/templates/learning_logs/topics.html
{%extends "learning_logs/base.html"%}

{%block content%}

<p>Topics</p>
<ul>
    {% for topic in topics%}
      <li>{{topic}}</li>
    {%empty%}
      <li>No topics have been added</li>
    {%endfor%}
</ul>
{%endblock content%}

users/templates/users/login.html
{%extends "learning_logs/base.html"%}

{%block content%}


  {%if form.errors%}
  <p>Your username and passwords are incorect</p>
  {%endif%}



<form method="post" action="{%url 'users:login'%}">
{%csrf_token%}
{{form.as_p}}
<button name="submit">login</button>
<input type="hidden" name="next" value="{url 'learning_logs:index'}"/>
</form>

{%endblock content%}

users/templates/users/register.html
{%block content%}

<form method="post" action="{%url 'users:register'%}">
    {%csrf_token%}
    {{form.as_p}}
    <button name="submit">Register</button>
    <input type="hiden" name="text" value="{%url 'learning_logs:index'%}"/>
</form>



{%endblock content%}